### ISSUE TITLE
No release since 2021-10-25/p5.9.20211024.0-2-g6f544dfc

### ISSUE THREAD

**Issue by gdupras** [universal-ctags/ctags-win32#14]
There are new commits regularly but the last release was in late October. Is this normal?

**Comment by k-takata** [comment]
Thank you for reporting.
This should be fixed in https://github.com/universal-ctags/ctags/pull/3256.

**Comment by k-takata** [comment]
Unfortunately, not fixed yet. Reopening.

**Comment by k-takata** [comment]
Fixed: https://github.com/universal-ctags/ctags-win32/releases/tag/2022-01-08%2Fp5.9.20220102.0-70-g1fad8423

**Comment by gdupras** [comment]
Great, thank you!
