### ISSUE TITLE
Should we include optscript.exe and mini-geany.exe?

### ISSUE THREAD

**Issue by k-takata** [universal-ctags/ctags-win32#16]
Currently, only `ctags.exe` and `readtags.exe` are included in the release package.
Should we also include `optscript.exe` and `mini-geany.exe` in the package?

**Comment by k-takata** [comment]
@masatake What do you think?

**Comment by masatake** [comment]
mini-geany is only for testing purposes. None wants to install it.

optscript.exe is for hard-core parser developers. So users of the binary package don't want to use and install it.

---

Last year I developed an interpreter and embedded it to ctags. The interpreter makes `--regex-<LANG>` option highly extensible. [pod.ctags](https://github.com/universal-ctags/ctags/blob/master/optlib/pod.ctags) is a parser using the interpreter.

optscript.exe is a stand-alone interpreter. With the command, a user can try the interpreter without ctags. It may help the user understand the language and its implementation:

```
[yamato@dev64]~/var/ctags-github% ./optscript 
OPT> 3 5 add
OPT<1> pstack
8
```

**Comment by k-takata** [comment]
Thank you for the explanation. So, no need to include them in the package.
Closing.
