### ISSUE TITLE
How to jump in different files by function name

### ISSUE THREAD

**Issue by xuzehao1109** [universal-ctags/ctags-win32#36]
please someboby tell me ,it make me depressed

**Comment by k-takata** [comment]
It may depend on your editor.

**Comment by xuzehao1109** [comment]
thanks，buy the way I used vscode&nbsp;editor,but it can jump in one file if function name in the same file .so it trouble me
&nbsp;


kiki
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月14日(星期二) 下午5:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [universal-ctags/ctags-win32] How to jump in different files by function name (Issue #36)





 
It may depend on your editor.
